name: Unit tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      max-parallel: 1
      matrix:
        include:
        - python-version: '3'
          os: ubuntu-latest
        - python-version: '2.7'
          os: ubuntu-20.04
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt pandas tabulate
          pip install -e .

      - name: GitHub Actions Pylint Report
        if: ${{ matrix.python-version != '2.7' }}
        run: |
          tool=github-action-pylint-report.py
          repo=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY
          tree=$repo/tree/$GITHUB_REF_NAME
          ./github-action-pylint-report.py xcp pylint-report.md $tree
          message_count=`tail -1 pylint-report.md|cut -d'|' -f2`
          echo -n "### [$tool]($tree/$tool): **xcp/\\*\\*/*.py**"  >>$GITHUB_STEP_SUMMARY
          echo " :rocket: #active Pylint messages: $message_count" >>$GITHUB_STEP_SUMMARY
          cat pylint-report.md                                     >>$GITHUB_STEP_SUMMARY

      - name: Run mypy checks
        if: ${{ matrix.python-version != '2.7' }}
        run: mypy

      - name: Run pytest with --cov and generate coverage reports
        run: |
          pytest --cov -rP
          coverage xml
          coverage html -d htmlcov-${{ matrix.python-version }}
          coverage html -d htmlcov-tests-${{ matrix.python-version }} --include="tests/*"
          diff-cover --compare-branch=origin/master --html-report coverage-diff-${{ matrix.python-version }}.html coverage.xml


      - name: Pylint
        run: |
          pylint --version
          pylint --exit-zero xcp/ tests/ setup.py
          pylint --exit-zero --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" xcp/ tests/ setup.py > pylint.txt
          diff-quality --compare-branch=origin/master --violations=pylint --html-report pylint-diff-${{ matrix.python-version }}.html pylint.txt

      - uses: actions/upload-artifact@v3
        with:
          name: Coverage and pylint reports
          path: |
            coverage-diff-${{ matrix.python-version }}.html
            pylint-diff-${{ matrix.python-version }}.html
            htmlcov-${{ matrix.python-version }}
            htmlcov-tests-${{ matrix.python-version }}
